server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boot-todo
    username: todo-user
    password: todo-user
    maximum-pool-size: 90
    auto-commit: false
    connection-timeout: 300000
  redis:
    host: localhost
    port: 6379
