doma:
  dialect: postgres
  query-timeout: 60
  naming: snake-lower-case

management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: httptrace, metrics

spring:
  session:
    store-type: redis

server:
  error:
    whitelabel:
      enabled: false