node {
   stage 'Setup'
   def mvnHome = tool 'maven3'

   stage 'Checkout'
   git url: 'https://github.com/gloryof/spring-boot-todo'

   stage 'Build'
   sh "${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean package -f springboot-todo/pom.xml"
   step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])

   stage 'Archive'
   archiveArtifacts artifacts: 'springboot-todo/target/springboot-todo-1.0.0-SNAPSHOT.jar', excludes: null
}